FROM debian:stable-slim
RUN apt-get update && apt-get install -y --no-install-recommends wget gnupg ca-certificates && rm -rf /var/lib/apt/lists/*
RUN wget -qO - https://www.mongodb.org/static/pgp/server-4.2.asc | apt-key add - && echo "deb http://repo.mongodb.org/apt/debian buster/mongodb-org/4.2 main" | tee /etc/apt/sources.list.d/mongodb-org-4.2.list
RUN apt-get update && apt-get install -y --no-install-recommends mongodb-org && rm -rf /var/lib/apt/lists/*
CMD mongod --bind_ip 0.0.0.0
