version: '3.4'

services:
  db:
    build:
      context: .
      dockerfile: .docker/Dockerfile-mongodb
    volumes:
    - ./.docker/docker-data/db:/data/db

  core:
    depends_on: 
    - db
    build:
      context: .
      dockerfile: .docker/Dockerfile-jimi_core
    volumes:
    - ./.docker/docker-data/settings.json:/jimi/data/settings.json:ro
    - ./.docker/docker-data/sessionPub.pem:/jimi/data/sessionPub.pem:ro
    - ./.docker/docker-data/sessionPriv.pem:/jimi/data/sessionPriv.pem:ro
    - ./.docker/docker-data/log:/jimi/log
    - ./.docker/docker-data/plugins:/jimi/plugins
    tty: true

  web:
    depends_on: 
    - db
    build:
      context: .
      dockerfile: .docker/Dockerfile-jimi_web
    volumes:
    - ./.docker/docker-data/settings.json:/jimi/data/settings.json:ro
    - ./.docker/docker-data/sessionPub.pem:/jimi/data/sessionPub.pem:ro
    - ./.docker/docker-data/sessionPriv.pem:/jimi/data/sessionPriv.pem:ro
    - ./.docker/docker-data/log:/jimi/log
    - ./.docker/docker-data/plugins:/jimi/plugins
    ports:
    - "5002:5002"
