# Build from debian
FROM debian:stable-slim

# Install requirements
RUN apt-get update && apt-get install -y --no-install-recommends python3-minimal python3-pip git && rm -rf /var/lib/apt/lists/*
RUN apt-get update && apt-get install -y --no-install-recommends python3-dev python3-setuptools python3-wheel gcc && rm -rf /var/lib/apt/lists/*

# Transfer jimi system files
RUN git clone https://github.com/z1pti3/jimi.git /jimi && pip3 install -r /jimi/requirements.txt

# Install jimi stable plugin requirements
#RUN pip3 install selenium
#RUN pip3 install numpy
#RUN pip3 install matplotlib
#RUN pip3 install sklearn
RUN pip3 install paramiko pywinrm smbprotocol scp

# Run
WORKDIR /jimi
CMD python3 jimi_core.py