version: '3.4'

services:
  db:
    image: mongo:latest
    volumes:
    - ./data/db:/data/db

  core:
    depends_on: 
    - db
    build:
      context: .
      dockerfile: Dockerfile-jimi_core
    volumes:
    - ./data/settings.json:/jimi/data/settings.json:ro
    - ./data/sessionPub.pem:/jimi/data/sessionPub.pem:ro
    - ./data/sessionPriv.pem:/jimi/data/sessionPriv.pem:ro
    - ./data/log:/jimi/log
    - ./data/plugins:/jimi/plugins
    tty: true

  web:
    depends_on: 
    - db
    build:
      context: .
      dockerfile: Dockerfile-jimi_web
    volumes:
    - ./data/settings.json:/jimi/data/settings.json:ro
    - ./data/sessionPub.pem:/jimi/data/sessionPub.pem:ro
    - ./data/sessionPriv.pem:/jimi/data/sessionPriv.pem:ro
    - ./data/log:/jimi/log
    - ./data/plugins:/jimi/plugins
    ports:
    - "5002:5002"
