version: '3.4'

services:
  db:
    image: mongo:latest
    volumes:
    - ./data/db:/data/db

  core:
    depends_on: 
    - db
    build:
      context: .
      dockerfile: Dockerfile-jimi_core
    volumes:
    - ./data:/home/jimi/jimi/data
    - ./data/log:/home/jimi/jimi/log
    - ./data/plugins:/home/jimi/jimi/plugins
    tty: true

  web:
    depends_on: 
    - db
    build:
      context: .
      dockerfile: Dockerfile-jimi_web
    volumes:
    - ./data:/home/jimi/jimi/data
    - ./data/log:/home/jimi/jimi/log
    - ./data/plugins:/home/jimi/jimi/plugins
    ports:
    - "443:443"
